uploads = []

[[generated]]
id = "sDCSOGMwT6P7a_wR1N85T"
uri = "file://artifacts/health-bite/assets/images/icon.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "wlYfIf8wyUTwciKCiuR5s"
uri = "file://health-bite.tar.gz"
type = "unspecified"
title = "Health Bite — React Native App"

[[outputs]]
id = "ocByjiQ23-9EMd-WfMhY2"
uri = "file://L1F23BSSE0201_ProjectDocument.pdf"
type = "pdf"
title = "L1F23BSSE0201_ProjectDocument.pdf"
