kind = "mobile"
previewPath = "/"
title = "Health Bite"
version = "1.0.0"
id = "artifacts/health-bite"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 18595

[services.development]
run = "pnpm --filter @workspace/health-bite run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/health-bite", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/health-bite", "run", "serve" ]

[services.env]
PORT = "18595"
BASE_PATH = "/"
