// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/health-dark/HealthDark.tsx": () => import("../components/mockups/health-dark/HealthDark.tsx")
};
